[package]
name = "chessmarkable"
version = "0.4.0"
authors = ["Linus <linus@cosmos-ink.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.33"
clap = "3.0.0-beta.1"
downcast-rs = "1.2"
env_logger = "0.7.1"
fxhash = "0.2"
lazy_static = "1.4.0"
log = "0.4.11"
pleco = "0.5.0"

[dependencies.libremarkable]
git = "https://github.com/LinusCDE/libremarkable.git"
branch = "feature/fix-evdev-crash-in-remux"

[dependencies.tokio]
version = "0.2.22"
features = [
    "blocking",
    "rt-core",
    "rt-threaded",
    "stream",
    "sync",
    "time"
]

[lib]
path = "src/lib/lib.rs"
