name: Build
on: [ push, pull_request ]

jobs:
  build_snapshot:
    name: Build snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        name: Release build
        with:
          use-cross: true
          command: build
          args: --release --target=armv7-unknown-linux-gnueabihf
