name: Check code
on: [ push, pull_request ]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Basic cargo check
        # TODO: Would be nice to get rid of all warnings at some
        #       point and make this check fail if any are found.
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: check
          args: --target=armv7-unknown-linux-gnueabihf

# TODO: Clippy, rustfmt and similar here as well
# See https://actions-rs.github.io/
